<?= $this->getContent() ?>

<h1>Organization</h1>
<section class="col-md-8 col-lg-9">
	<h1>Control Centers Organization</h1>
	
	<div class="row">
	
		<article class="col-md-6 col-lg-4">
			<img src="img/ControlCenterOrganization-sm.jpg" alt="CCOrg"/>
		</article>
		
		<article class="col-md-6 col-lg-4">
			<ul>Agenda: 
			<li>C3 - Command and Control Center - main center of the ship</li> 
			<li>Bridge - Reserve Command Center of the ship</li>
			<li>DC2 - Damage Control Center - observation and control of life support systems, firefighting systems and hull integrity systems onboard</li>
			<li>E2C2 - Energy and Engine Control Center - observation and control of energy generators, unified propulsion instalations system, other equipment</li>
			<li>SC2 - Scientific Control Center - main labs and scientific equipment onboard is in this center</li>  
		</article>
		
		<article class="col-md-6 col-lg-4">
			This is the main control centers onboard. This scheme is the backbone of the ship crew organization scheme.
		</article>
		
</section>

